export const REDEEM_CODES = {
  // 徽章碼 — 交換提問者 (Week 1)
  "B-EQ-K1U8": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-J9T1": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-H8S2": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-G7R3": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-F6Q4": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-E5P5": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-D4N6": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-B2L8": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-C3M7": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },
  "B-EQ-A1K9": { type: "badge", rewardId: "badge-exchange-questioner", maxUses: 5 },

  // 徽章碼 — 貨幣溯源者 (Week 2)
  "B-OS-K3M7": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-T1P9": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-N8A2": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-Z4J6": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-Q2W5": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-R7C1": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-H9X3": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-L5D8": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-V6G4": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-Y1B0": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-F3N9": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-U8K2": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-M4T7": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-E2R6": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-S9L1": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-C5Z3": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-W7A4": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-J0H8": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-D6Q5": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },
  "B-OS-X1V2": { type: "badge", rewardId: "badge-origin-seeker", maxUses: 5 },

  // 徽章碼 — 價值分辨者 (Week 3)
  "B-OS-P3K8": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-G5M2": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-T9D4": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-A1R7": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-N6Y3": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-H2F9": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-Z8W5": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-L4B1": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-V7S0": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },
  "B-OS-E6U3": { type: "badge", rewardId: "badge-value-discerner", maxUses: 5 },

  // 徽章碼 — 成本偵探者 (Week 4)
  "B-CD-2DY2": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-46A3": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-7UCV": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-AUGZ": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-GHTW": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-HRVJ": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-JHHE": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-QBAC": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-XDA2": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },
  "B-CD-XZUQ": { type: "badge", rewardId: "badge-cost-detective", maxUses: 5 },

  // 卡片碼 — 交換卡關點 (Week 1)
  "C-EF-K1U8": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-J9T1": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-H8S2": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-G7R3": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-F6Q4": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-E5P5": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-D4N6": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-C3M7": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-B2L8": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },
  "C-EF-A1K9": { type: "card", rewardId: "card-exchange-bottleneck", maxUses: 5 },

  // 卡片碼 — 共識貨幣 (Week 2)
  "C-CC-G8Y6": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-N1L5": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-R9J2": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-V5H4": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-L6T7": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-T8Q1": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-H3V4": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-W4D3": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-J7B1": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-B5Z7": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-F9K2": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-S8P3": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-Q2S9": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-D1R5": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-P2N6": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-X6F8": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-Z3M8": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-K4W9": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-Y4G6": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },
  "C-CC-M7X3": { type: "card", rewardId: "card-consensus-currency", maxUses: 5 },

  // 卡片碼 — 價格的秘密 (Week 3)
  "C-SP-K3M7": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-H9T4": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-R2X8": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-N5J6": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-W7B3": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-P4D9": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-Y6F2": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-Q8L5": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-V3N7": { type: "card", rewardId: "card-price-secret", maxUses: 5 },
  "C-SP-M2K4": { type: "card", rewardId: "card-price-secret", maxUses: 5 },

  // 卡片碼 — 成本的真相 (Week 4)
  "C-CT-4B2R": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-4FZQ": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-6NWJ": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-93MD": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-CPDN": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-CUK5": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-MJEG": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-NVGZ": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-UD8P": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },
  "C-CT-XW76": { type: "card", rewardId: "card-cost-truth", maxUses: 5 },

  // 卡片碼 — 價格不等於價值（直播限定）
  "C-PV-A1K9": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-B2L8": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-C3M7": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-D4N6": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-E5P5": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-F6Q4": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-G7R3": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-H8S2": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-J9T1": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },
  "C-PV-K1U8": { type: "card", rewardId: "card-price-vs-value", maxUses: 5 },

  // 徽章碼 — 價值觀察者（直播限定）
  "B-VO-A7K2": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-B2L8": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-C8P4": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-E3X1": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-H3S8": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-J7D2": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-K7S6": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-K8W3": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-M2X5": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-P3L8": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-Q8M3": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-R2Z7": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-R6L4": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-S9K1": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-T6Q1": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-U9L1": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-X9M4": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },
  "B-VO-Y4F6": { type: "badge", rewardId: "badge-value-observer", maxUses: 5 },

  // 徽章碼 — 初學者徽章
  "X8F2K9Q": { type: "badge", rewardId: "badge-beginner", maxUses: 99 },
};

export const REWARDS = {
  "badge-exchange-questioner": {
    type: "badge",
    name: "交換提問者",
    description: "完成 Week 1 財商概念測驗，理解交換的本質",
    week: 1,
    image: "/images/W1 交換提問者.png",
  },
  "badge-origin-seeker": {
    type: "badge",
    name: "貨幣溯源者",
    description: "完成 Week 2 財商概念測驗，理解金錢的起源與信任",
    week: 2,
    image: "/images/W2 貨幣溯源者徽章.png",
  },
  "badge-value-discerner": {
    type: "badge",
    name: "價值分辨者",
    description: "完成 Week 3 財商概念測驗，理解價值與價格的差異",
    week: 3,
    image: "/images/W3 價值分辨者 徽章.png",
  },
  "badge-cost-detective": {
    type: "badge",
    name: "成本偵探者",
    description: "完成 Week 4 財商概念測驗，理解成本與利潤的關係",
    week: 4,
    image: "/images/W4_成本偵探者_徽章.png",
  },
  "badge-value-observer": {
    type: "badge",
    name: "價值觀察者",
    description: "理解價值與價格的差異",
    week: 0,
    image: "/images/財商思維啟航 直播體驗徽章 1.png",
  },
  "badge-beginner": {
    type: "badge",
    name: "初學者徽章",
    description: "開始財商學習之旅",
    week: 0,
    image: "/images/財商思維啟航 直播體驗徽章 1.png",
  },
  "badge-value-detective": {
    type: "badge",
    name: "價值偵探",
    description: "完成 VD-0419 直播限定測驗，理解機會成本與情境定價",
    week: 0,
    image: "/images/VD-0419_價值偵探徽章.png",
  },
  "card-exchange-bottleneck": {
    type: "card",
    name: "交換的卡關點",
    description: "合作始於交換：我有什麼？需求未合、時間未合、價值難量",
    image: "/images/W1_交換的卡關點_v1_2.png",
  },
  "card-consensus-currency": {
    type: "card",
    name: "共識貨幣",
    description: "錢的樣子一直在變，但讓它成為錢的那件事，從來沒變過",
    image: "/images/W2_共識貨幣_v1_2.png",
  },
  "card-price-secret": {
    type: "card",
    name: "價格的秘密",
    description: "價格不是老闆隨便寫的，它是供給和需求互相拉扯出來的數字",
    image: "/images/W3_價格的秘密_v1_2.png",
  },
  "card-cost-truth": {
    type: "card",
    name: "成本的真相",
    description: "收入不等於利潤。每一個價格背後，都藏著老闆在算的一本帳",
    image: "/images/W4_成本的真相_卡片.png",
  },
  "card-price-vs-value": {
    type: "card",
    name: "價格不等於價值（直播限定）",
    description: "價格是數字，價值要看情境",
    image: "/images/財商思維啟航 直播卡片 1.png",
  },
};

export const WEEKS = [
  {
    id: "week1",
    title: "Week 1",
    question: "如果世界沒有錢，真的會更公平嗎？",
    badgeId: "badge-exchange-questioner",
    route: "/Week1Practice",
    available: true,
  },
  {
    id: "week2",
    title: "Week 2",
    question: "價格是什麼？它跟價值一樣嗎？",
    badgeId: "badge-origin-seeker",
    route: "/Week2Practice",
    available: false,
  },
  {
    id: "week3",
    title: "Week 3",
    question: "為什麼有些東西貴但大家還是搶著買？",
    badgeId: "badge-value-discerner",
    route: "/Week3Practice",
    available: false,
  },
  {
    id: "week4",
    title: "Week 4",
    question: "老闆賣東西真的賺那麼多嗎？",
    badgeId: "badge-cost-detective",
    route: "/Week4Practice",
    available: false,
  },
];