// 題庫 Part 2：資產vs消耗品、借貸vs利息vs信用、保險vs儲蓄vs投資、收入vs價值交換、主動vs被動收入

export const asset_vs_consumption_good = [
  { type:"multiple_choice", question:"以下哪一個比較接近「資產」？", options:["一張會定期配息的股票","一包今天吃完的洋芋片"], answer:"一張會定期配息的股票", explanation:"資產通常是未來可能繼續帶來價值或收入的東西。" },
  { type:"multiple_choice", question:"一瓶洗髮精用完就沒了，這比較接近？", options:["消耗品","資產"], answer:"消耗品", explanation:"使用後會越來越少，最後用完的東西，通常是消耗品。" },
  { type:"multiple_choice", question:"一間出租中的房子，每個月會帶來租金，這比較接近？", options:["資產","消耗品"], answer:"資產", explanation:"它不只存在，還可能持續帶來收入，所以比較接近資產。" },
  { type:"multiple_choice", question:"買來自己吃掉的便當，這比較接近？", options:["消耗品","資產"], answer:"消耗品", explanation:"吃完就沒有了，不會在未來繼續幫你帶來價值。" },
  { type:"multiple_choice", question:"存放在銀行裡、之後還能使用的存款，這比較接近？", options:["資產","消耗品"], answer:"資產", explanation:"存款仍然保有價值，未來還可以使用，所以比較接近資產。" },
  { type:"multiple_choice", question:"以下哪一句更接近「資產」的意思？", options:["未來還可能幫我，或帶來價值的東西","現在用了很開心的東西"], answer:"未來還可能幫我，或帶來價值的東西", explanation:"資產的重點不是當下開心，而是未來還可能繼續幫你。" },
  { type:"multiple_choice", question:"「消耗品」的特點是？", options:["使用後會減少或消失","價值會不斷增加"], answer:"使用後會減少或消失", explanation:"消耗品在使用過程中會逐漸減少直到用完。" },
  { type:"multiple_choice", question:"一塊黃金，這比較接近？", options:["資產","消耗品"], answer:"資產", explanation:"黃金通常能保存價值，未來也可能賣出，所以比較接近資產。" },
  { type:"multiple_choice", question:"一盒鉛筆，這是？", options:["消耗品","資產"], answer:"消耗品", explanation:"鉛筆寫完就沒了，屬於「消耗品」。" },
  { type:"multiple_choice", question:"爸爸買了一塊土地，這是？", options:["資產","消耗品"], answer:"資產", explanation:"土地有長期保值甚至增值的特性，是典型的「資產」。" },
  { type:"multiple_choice", question:"一袋麵粉，這比較接近？", options:["消耗品","資產"], answer:"消耗品", explanation:"麵粉是烹飪材料，使用後就沒了，屬於「消耗品」。" },
  { type:"multiple_choice", question:"一台可以出租賺錢的機器，這是？", options:["資產","消耗品"], answer:"資產", explanation:"能帶來收益的機器，屬於「資產」。" },
  { type:"multiple_choice", question:"牙膏是？", options:["消耗品","資產"], answer:"消耗品", explanation:"牙膏用完就沒了，屬於「消耗品」。" },
  { type:"multiple_choice", question:"一塊幾年後仍然有人願意購買的黃金手錶，這比較接近？", options:["資產","消耗品"], answer:"資產", explanation:"如果它未來還保有價值，甚至有人願意買，就比較接近資產。" },
  { type:"multiple_choice", question:"為什麼了解「資產」和「消耗品」的差別很重要？", options:["幫助做更好的消費決定","讓人更有名"], answer:"幫助做更好的消費決定", explanation:"知道什麼是資產、什麼是消耗品，能幫助我們判斷如何花錢更有價值。" },
  { type:"multiple_choice", question:"股票屬於什麼？", options:["資產","消耗品"], answer:"資產", explanation:"股票有金融價值，可以保存或賣出，屬於「資產」。" },
  { type:"multiple_choice", question:"一包糖果是？", options:["消耗品","資產"], answer:"消耗品", explanation:"糖果吃了就沒有了，是「消耗品」。" },
  { type:"multiple_choice", question:"一棟可以出租的公寓，這是？", options:["資產","消耗品"], answer:"資產", explanation:"公寓可以保值且帶來租金收入，是很好的「資產」。" },
  { type:"multiple_choice", question:"衛生紙是？", options:["消耗品","資產"], answer:"消耗品", explanation:"衛生紙用完就沒了，屬於「消耗品」。" },
  { type:"multiple_choice", question:"「資產」和「消耗品」最主要的差別是？", options:["資產能長期保有價值，消耗品用後消失","資產比消耗品貴"], answer:"資產能長期保有價值，消耗品用後消失", explanation:"資產的重點是長期保有價值，消耗品的特點是用完就沒了。" }
];

export const loan_vs_interest_vs_credit = [
  { type:"multiple_choice", question:"向銀行借 10000 元，這個行為叫做？", options:["借貸","利息"], answer:"借貸", explanation:"向別人或機構借錢的行為就是「借貸」。" },
  { type:"multiple_choice", question:"借了 1000 元，一年後要還 1060 元，多出的 60 元叫做？", options:["利息","信用"], answer:"利息", explanation:"借錢後額外支付的費用叫「利息」。" },
  { type:"multiple_choice", question:"「這個人每次借錢都準時還，大家都信任他。」這說明他有良好的？", options:["信用","利息"], answer:"信用", explanation:"準時履行承諾讓人信任你，這就是「信用」。" },
  { type:"multiple_choice", question:"為什麼銀行要向借款人收取利息？", options:["因為貸款有風險，利息是補償","因為銀行想賺更多錢"], answer:"因為貸款有風險，利息是補償", explanation:"銀行借出的錢有無法收回的風險，利息是對這個風險的補償。" },
  { type:"multiple_choice", question:"小明向爸爸借 200 元，兩週後還了 200 元。這叫做？", options:["借貸並清償","利息"], answer:"借貸並清償", explanation:"借了錢後還清，整個過程是「借貸」行為。" },
  { type:"multiple_choice", question:"信用卡的「信用」是指？", options:["先消費後還款的能力和信任","卡片的顏色"], answer:"先消費後還款的能力和信任", explanation:"信用卡讓你先花錢後還款，背後是對你還款能力的信任。" },
  { type:"multiple_choice", question:"借 1000 元，利率 5%，一年後要多還多少元？", options:["50 元","500 元"], answer:"50 元", explanation:"1000 × 5% = 50 元，這就是一年的「利息」。" },
  { type:"multiple_choice", question:"「欠錢不還」會影響什麼？", options:["信用","利息"], answer:"信用", explanation:"不守承諾還錢會讓別人不再信任你，損害你的「信用」。" },
  { type:"multiple_choice", question:"信用良好的人向銀行借錢，利息通常？", options:["比較低","比較高"], answer:"比較低", explanation:"信用好代表風險小，銀行會給予較低的利率。" },
  { type:"multiple_choice", question:"向同學借了橡皮擦，用完後還給他，這是？", options:["借貸（借物品）","利息"], answer:"借貸（借物品）", explanation:"借東西也是「借貸」的一種，不僅限於借錢。" },
  { type:"multiple_choice", question:"「利息」的計算基礎通常是？", options:["借款金額和利率","信用分數"], answer:"借款金額和利率", explanation:"利息 = 借款金額 × 利率 × 時間。" },
  { type:"multiple_choice", question:"建立良好信用的方法是？", options:["每次都準時還款","盡量多借錢"], answer:"每次都準時還款", explanation:"準時還款是建立良好信用最重要的方法。" },
  { type:"multiple_choice", question:"借了錢沒有還，叫做？", options:["違約（信用破產）","賺到了"], answer:"違約（信用破產）", explanation:"不還錢是違反借貸契約的行為，會嚴重損害個人信用。" },
  { type:"multiple_choice", question:"小美的信用非常好，這意味著她可以？", options:["更容易借到錢，且利率更低","不需要還錢"], answer:"更容易借到錢，且利率更低", explanation:"信用好讓人更願意借錢給你，而且條件更優惠。" },
  { type:"multiple_choice", question:"借貸、利息、信用三者中，「信用」是？", options:["別人對你還款能力的信任","借錢的行為"], answer:"別人對你還款能力的信任", explanation:"信用是長期建立的信任感，與借錢和利息都有關係。" },
  { type:"multiple_choice", question:"利率越高，表示借錢的？", options:["成本越高","風險越低"], answer:"成本越高", explanation:"利率高代表需要支付更多的利息，借錢的成本就越高。" },
  { type:"multiple_choice", question:"「分期付款」是哪一種行為的應用？", options:["借貸","儲蓄"], answer:"借貸", explanation:"分期付款是先享用商品，之後分批償還，是借貸的一種形式。" },
  { type:"multiple_choice", question:"媽媽說：「一定要準時繳信用卡帳單。」她在保護什麼？", options:["信用","利息"], answer:"信用", explanation:"準時繳費能維護良好的信用記錄。" },
  { type:"multiple_choice", question:"銀行貸款利率 3%，表示借 1000 元一年要多還？", options:["30 元","300 元"], answer:"30 元", explanation:"1000 × 3% = 30 元，這就是一年需要支付的「利息」。" },
  { type:"multiple_choice", question:"以下哪一個行為最能幫助建立良好的信用？", options:["每次都準時還款與履約","一直避免面對付款責任"], answer:"每次都準時還款與履約", explanation:"信用來自別人對你是否可靠的信任，準時還款和履約都能建立信用。" }
];

export const insurance_vs_saving_vs_investment = [
  { type:"multiple_choice", question:"每月繳費，生病時可以獲得理賠，這是？", options:["保險","儲蓄"], answer:"保險", explanation:"定期繳費換取發生意外時的保障，就是「保險」。" },
  { type:"multiple_choice", question:"把零用錢存到銀行，這是？", options:["儲蓄","投資"], answer:"儲蓄", explanation:"把錢存起來不花的行為就是「儲蓄」。" },
  { type:"multiple_choice", question:"買了一家公司的股票，希望未來賺錢，這是？", options:["投資","儲蓄"], answer:"投資", explanation:"花錢買資產，期望未來獲得報酬，就是「投資」。" },
  { type:"multiple_choice", question:"和銀行儲蓄相比，股票投資通常比較？", options:["波動較大，但也可能有較高報酬","一樣安全，而且一定賺更多"], answer:"波動較大，但也可能有較高報酬", explanation:"投資通常有較大波動，不保證賺錢，但有機會得到較高報酬。" },
  { type:"multiple_choice", question:"以下哪一句最符合「保險」？", options:["先付一筆費用，換未來發生意外時的保障","把錢放著不動，等它慢慢變多"], answer:"先付一筆費用，換未來發生意外時的保障", explanation:"保險的重點不是賺錢，而是先做好保護。" },
  { type:"multiple_choice", question:"健康保險屬於？", options:["保險","投資"], answer:"保險", explanation:"健康保險是保護健康的風險管理工具，屬於「保險」。" },
  { type:"multiple_choice", question:"買基金希望獲得回報，這是？", options:["投資","保險"], answer:"投資", explanation:"把錢投入資本市場期望獲利，就是「投資」。" },
  { type:"multiple_choice", question:"「每月存 500 元在活期存款」是什麼行為？", options:["儲蓄","投資"], answer:"儲蓄", explanation:"把錢放在銀行活期存款，風險極低，屬於「儲蓄」。" },
  { type:"multiple_choice", question:"投資股票，股價下跌，這說明投資有什麼？", options:["風險","保障"], answer:"風險", explanation:"投資可能帶來損失，這就是「投資風險」。" },
  { type:"multiple_choice", question:"火災保險的作用是？", options:["房子失火時可以獲得賠償","讓房子增值"], answer:"房子失火時可以獲得賠償", explanation:"保險在發生損失時提供補償，這是保險的核心功能。" },
  { type:"multiple_choice", question:"買房子出租給別人，每月收租金，這是？", options:["投資","儲蓄"], answer:"投資", explanation:"用錢買資產並獲取報酬，屬於「投資」。" },
  { type:"multiple_choice", question:"一個好的理財計畫應該包含？", options:["保險、儲蓄和投資都有","只要投資就好"], answer:"保險、儲蓄和投資都有", explanation:"三者各有功能：保險保障、儲蓄存錢、投資增值。" },
  { type:"multiple_choice", question:"以下哪個風險最小？", options:["銀行儲蓄","股票投資"], answer:"銀行儲蓄", explanation:"銀行儲蓄風險極低，投資股票風險較高。" },
  { type:"multiple_choice", question:"以下哪個報酬潛力最高？", options:["股票投資","銀行儲蓄"], answer:"股票投資", explanation:"投資風險較高，但相對地報酬潛力也較大。" },
  { type:"multiple_choice", question:"每月繳汽車保險費，這是？", options:["保險","儲蓄"], answer:"保險", explanation:"繳費換取車禍等意外的保障，是「保險」。" },
  { type:"multiple_choice", question:"定期存款的報酬通常比股票？", options:["低，但比較安全","高，且更安全"], answer:"低，但比較安全", explanation:"定期存款屬於儲蓄，安全性高但報酬率低。" },
  { type:"multiple_choice", question:"「投資」的核心概念是？", options:["現在花錢，期望未來獲得更多回報","把錢存起來不動"], answer:"現在花錢，期望未來獲得更多回報", explanation:"投資是以金錢換取未來更大回報的行為。" },
  { type:"multiple_choice", question:"「儲蓄」的核心概念是？", options:["把錢保存起來，不立即花掉","冒險賺更多錢"], answer:"把錢保存起來，不立即花掉", explanation:"儲蓄就是延遲消費，把錢保存下來。" },
  { type:"multiple_choice", question:"旅遊保險的作用是？", options:["出遊遇到意外時提供保障","讓旅遊費用更便宜"], answer:"出遊遇到意外時提供保障", explanation:"旅遊保險在旅途中發生意外時提供財務保障。" },
  { type:"multiple_choice", question:"保險費是「花掉的錢」，但其意義是？", options:["換取未來風險的保障","浪費了錢"], answer:"換取未來風險的保障", explanation:"雖然保險費是支出，但換來的是發生意外時的財務保護。" }
];

export const income_vs_value_exchange = [
  { type:"multiple_choice", question:"每月收到的薪水是什麼？", options:["收入","價值交換"], answer:"收入", explanation:"工作後獲得的金錢叫做「收入」。" },
  { type:"multiple_choice", question:"爸爸上班工作，公司付他薪水，這整個過程是？", options:["價值交換","純粹的收入"], answer:"價值交換", explanation:"爸爸提供勞動力（價值），公司給予薪水（價值），這是雙方的價值交換。" },
  { type:"multiple_choice", question:"「收入」是指？", options:["通過工作或其他方式獲得的金錢","消費商品"], answer:"通過工作或其他方式獲得的金錢", explanation:"收入是金錢流入的總稱。" },
  { type:"multiple_choice", question:"買東西時，買方付錢、賣方給商品，這是？", options:["價值交換","收入"], answer:"價值交換", explanation:"雙方都提供了對方想要的東西，這是「價值交換」。" },
  { type:"multiple_choice", question:"打工一小時賺 180 元，這 180 元是打工者的？", options:["收入","支出"], answer:"收入", explanation:"提供勞動換來的金錢就是「收入」。" },
  { type:"multiple_choice", question:"市場上所有的買賣，本質上都是？", options:["價值交換","單純的收入"], answer:"價值交換", explanation:"所有交易都是雙方互相提供對方需要的價值。" },
  { type:"multiple_choice", question:"醫生提供看診服務，病人付掛號費，這是？", options:["價值交換","借貸"], answer:"價值交換", explanation:"醫生的服務和病人的金錢，雙方各自提供了對方需要的東西。" },
  { type:"multiple_choice", question:"老師教學，學生付學費，這是？", options:["價值交換","免費服務"], answer:"價值交換", explanation:"教育服務換取學費，是一種「價值交換」。" },
  { type:"multiple_choice", question:"收入的來源不包括？", options:["花掉積蓄","工作薪水"], answer:"花掉積蓄", explanation:"花掉積蓄是支出，不是收入。收入是金錢的流入。" },
  { type:"multiple_choice", question:"「價值交換」中，雙方交換的可以是？", options:["金錢、商品或服務","只有金錢"], answer:"金錢、商品或服務", explanation:"價值交換可以用金錢、實物或服務，形式多樣。" },
  { type:"multiple_choice", question:"獲得獎學金，這算是一種？", options:["收入","支出"], answer:"收入", explanation:"獎學金是獲得的金錢，屬於「收入」。" },
  { type:"multiple_choice", question:"農夫賣出蔬菜，獲得金錢，對農夫來說，蔬菜的銷售是？", options:["價值交換的一部分","浪費"], answer:"價值交換的一部分", explanation:"農夫用蔬菜換取金錢，是「價值交換」。" },
  { type:"multiple_choice", question:"每月領到零用錢，這對孩子來說是？", options:["收入","支出"], answer:"收入", explanation:"領到的零用錢是金錢的流入，屬於「收入」。" },
  { type:"multiple_choice", question:"幫同學補習，同學給你 100 元，這是？", options:["收入（透過價值交換獲得）","支出"], answer:"收入（透過價值交換獲得）", explanation:"提供服務換取金錢，獲得的 100 元是你的「收入」。" },
  { type:"multiple_choice", question:"「公平的價值交換」是指？", options:["雙方都覺得自己得到的值得","一方獲得更多利益"], answer:"雙方都覺得自己得到的值得", explanation:"公平的交換中，雙方都認為自己的付出換到了值得的東西。" },
  { type:"multiple_choice", question:"賣二手玩具得到 200 元，這 200 元是？", options:["收入","支出"], answer:"收入", explanation:"賣東西得到的金錢是「收入」。" },
  { type:"multiple_choice", question:"所有的工作，本質上都是把自己的什麼換成金錢？", options:["時間和技能（價值）","快樂"], answer:"時間和技能（價值）", explanation:"工作是把個人的時間、技能等「價值」換成收入。" },
  { type:"multiple_choice", question:"以下哪一個不是「收入」？", options:["付了 200 元買書","賣了東西得 200 元"], answer:"付了 200 元買書", explanation:"付錢是支出，賣東西得錢才是收入。" },
  { type:"multiple_choice", question:"如果你幫家裡打掃，爸媽給你零用錢，這是？", options:["價值交換（服務換金錢）","借貸"], answer:"價值交換（服務換金錢）", explanation:"提供打掃服務換取零用錢，是一種「價值交換」。" },
  { type:"multiple_choice", question:"「收入」和「價值交換」的關係是？", options:["收入通常是價值交換的結果","兩者完全無關"], answer:"收入通常是價值交換的結果", explanation:"大多數收入都來自提供了某種價值（工作、服務、商品），即價值交換。" }
];

export const active_vs_passive_income = [
  { type:"multiple_choice", question:"每天上班工作才能領到薪水，這是？", options:["主動收入","被動收入"], answer:"主動收入", explanation:"需要持續付出時間和勞力才能獲得的收入是「主動收入」。" },
  { type:"multiple_choice", question:"把錢存在銀行，每月自動收到利息，這是？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"不需要額外工作就能自動獲得的收入是「被動收入」。" },
  { type:"multiple_choice", question:"打工時薪 150 元，工作才有錢，這是？", options:["主動收入","被動收入"], answer:"主動收入", explanation:"必須付出時間勞力才能獲得，屬於「主動收入」。" },
  { type:"multiple_choice", question:"房東把房子出租，每月收到租金，這是？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"不需要每天工作就能定期收到錢，是「被動收入」。" },
  { type:"multiple_choice", question:"主動收入的特點是？", options:["需要持續付出時間才能獲得","不用工作自動有錢"], answer:"需要持續付出時間才能獲得", explanation:"主動收入與你投入的時間和勞力直接相關。" },
  { type:"multiple_choice", question:"被動收入的特點是？", options:["不需要持續工作也能獲得","必須每天上班才有"], answer:"不需要持續工作也能獲得", explanation:"被動收入可以在你不工作的時候繼續流入。" },
  { type:"multiple_choice", question:"投資股票，每年收到股息（分紅），這是？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"股息是投資帶來的自動收益，屬於「被動收入」。" },
  { type:"multiple_choice", question:"如果你停止工作，主動收入會？", options:["停止進來","繼續進來"], answer:"停止進來", explanation:"主動收入依賴你的工作，停止工作就停止收入。" },
  { type:"multiple_choice", question:"如果你停止工作，被動收入通常？", options:["仍然繼續進來","立刻停止"], answer:"仍然繼續進來", explanation:"被動收入不依賴你每天工作，可以持續流入。" },
  { type:"multiple_choice", question:"作者寫了一本書，每賣出一本都有版稅收入，這是？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"書寫好後持續帶來版稅，不需要每次都重新工作，是「被動收入」。" },
  { type:"multiple_choice", question:"律師每處理一個案件才獲得酬勞，這是？", options:["主動收入","被動收入"], answer:"主動收入", explanation:"必須親自工作才能獲得報酬，是「主動收入」。" },
  { type:"multiple_choice", question:"在 YouTube 上傳影片，廣告費每月自動匯入，這是？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"影片上傳後持續帶來廣告收入，不需要每天重新工作，是「被動收入」。" },
  { type:"multiple_choice", question:"為什麼很多人想要「被動收入」？", options:["即使不工作也有錢進來，更自由","因為被動收入一定比主動收入多"], answer:"即使不工作也有錢進來，更自由", explanation:"被動收入讓人有財務上的自由，不必時時刻刻工作。" },
  { type:"multiple_choice", question:"主動收入通常需要投入什麼？", options:["時間和勞力","一次性的初始資金"], answer:"時間和勞力", explanation:"主動收入的代價是持續的時間和體力投入。" },
  { type:"multiple_choice", question:"被動收入通常需要先投入什麼？", options:["初始的時間、金錢或努力","什麼都不需要"], answer:"初始的時間、金錢或努力", explanation:"大多數被動收入都需要前期投資或努力，才能持續帶來報酬。" },
  { type:"multiple_choice", question:"爸爸下班後還要兼差才有那份收入，兼差的收入是？", options:["主動收入","被動收入"], answer:"主動收入", explanation:"需要額外付出時間和勞力的收入是「主動收入」。" },
  { type:"multiple_choice", question:"放在定期存款的錢每年自動產生的利息是？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"定期存款利息自動產生，不需要工作，是「被動收入」。" },
  { type:"multiple_choice", question:"一般上班族的薪水通常是？", options:["主動收入","被動收入"], answer:"主動收入", explanation:"工作才有薪水，不工作就沒有，是「主動收入」。" },
  { type:"multiple_choice", question:"小明創業開了一家店，店面運作不需要他每天在場，每月自動有盈利，這是？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"不需要親自在場工作就能獲得的收入，是「被動收入」。" },
  { type:"multiple_choice", question:"哪一種收入更有利於財務自由？", options:["被動收入","主動收入"], answer:"被動收入", explanation:"被動收入讓你在不工作時也有錢進來，更容易實現財務自由。" }
];