// 題庫 Part 1：需要vs喜歡、價值vs價格、交換vs金錢、支出vs消費、預算vs儲蓄vs記帳

export const need_vs_like = [
  { type:"multiple_choice", question:"小明已經有一個可以正常使用的書包了，還想買最新款聯名書包，這比較接近？", options:["需要","喜歡"], answer:"喜歡", explanation:"如果原本的書包還能正常使用，再買新款比較接近想要，不是基本需要。" },
  { type:"multiple_choice", question:"小美的雨傘昨天壞掉了，今天又下大雨，她去買一把新雨傘，這比較接近？", options:["需要","喜歡"], answer:"需要", explanation:"原本的雨傘壞了，又遇到下雨，這時買雨傘是在解決眼前的問題。" },
  { type:"multiple_choice", question:"小華已經有三雙可以穿的球鞋，還想再買一雙限量款，這比較接近？", options:["需要","喜歡"], answer:"喜歡", explanation:"已經有足夠可以穿的鞋子，再買限量款比較接近個人喜好。" },
  { type:"multiple_choice", question:"冬天到了，小明原本的外套已經太小穿不下，只好買一件新的保暖外套，這比較接近？", options:["需要","喜歡"], answer:"需要", explanation:"原本的外套已經不能穿了，新外套是在解決保暖問題。" },
  { type:"multiple_choice", question:"手機殼已經破掉，手機容易摔壞，所以去買一個新的，這比較接近？", options:["需要","喜歡"], answer:"需要", explanation:"這時候手機殼是在保護手機，不只是裝飾，所以比較接近需要。" },
  { type:"multiple_choice", question:"生病時看醫生，這是？", options:["需要","喜歡"], answer:"需要", explanation:"看醫生是保障健康的必要行為，屬於「需要」。" },
  { type:"multiple_choice", question:"想要訂閱一個遊戲平台，這是？", options:["需要","喜歡"], answer:"喜歡", explanation:"遊戲是娛樂，不是生活必需品，屬於「喜歡」。" },
  { type:"multiple_choice", question:"上學要用的課本，這是？", options:["需要","喜歡"], answer:"需要", explanation:"課本是學習必備的工具，屬於「需要」。" },
  { type:"multiple_choice", question:"想吃最新口味的冰淇淋，這是？", options:["需要","喜歡"], answer:"喜歡", explanation:"冰淇淋是零食，不是生活必需品，屬於「喜歡」。" },
  { type:"multiple_choice", question:"每天刷牙用的牙膏，這是？", options:["需要","喜歡"], answer:"需要", explanation:"牙膏是維持衛生健康的必需品，屬於「需要」。" },
  { type:"multiple_choice", question:"小明想買一個最新款造型手機殼，這比較接近？", options:["需要","喜歡"], answer:"喜歡", explanation:"這裡強調的是新款造型，比較接近個人喜好，而不是基本需要。" },
  { type:"multiple_choice", question:"下雨天需要雨傘，這是？", options:["需要","喜歡"], answer:"需要", explanation:"雨傘可以保護身體不淋濕，屬於實際的「需要」。" },
  { type:"multiple_choice", question:"想要買一張喜歡歌手的演唱會門票，這是？", options:["需要","喜歡"], answer:"喜歡", explanation:"演唱會是娛樂活動，屬於「喜歡」。" },
  { type:"multiple_choice", question:"每天上學搭公車，這是？", options:["需要","喜歡"], answer:"需要", explanation:"交通工具是上學的必要手段，屬於「需要」。" },
  { type:"multiple_choice", question:"媽媽原本的鍋子已經壞掉了，所以買一個新的鍋子，這比較接近？", options:["需要","喜歡"], answer:"需要", explanation:"原本能用的東西壞掉了，買新的鍋子是在解決實際生活問題。" },
  { type:"multiple_choice", question:"小華想買一款新的貼紙組，這是？", options:["需要","喜歡"], answer:"喜歡", explanation:"貼紙是裝飾品，不是生活必需品，屬於「喜歡」。" },
  { type:"multiple_choice", question:"睡覺用的被子，這是？", options:["需要","喜歡"], answer:"需要", explanation:"被子是保暖的必需品，屬於「需要」。" },
  { type:"multiple_choice", question:"想要一雙名牌球鞋，這是？", options:["需要","喜歡"], answer:"喜歡", explanation:"名牌球鞋主要是品牌吸引力，並非基本生活所需，屬於「喜歡」。" },
  { type:"multiple_choice", question:"喝水、吃飯、穿衣服，這些都屬於？", options:["需要","喜歡"], answer:"需要", explanation:"這三樣都是維持生命和生活的基本需求，屬於「需要」。" },
  { type:"multiple_choice", question:"爸爸說：「這個可以買，但不是非買不可。」這代表這是？", options:["需要","喜歡"], answer:"喜歡", explanation:"「非買不可」才是需要，「可買可不買」就是喜歡。" }
];

export const value_vs_price = [
  { type:"multiple_choice", question:"「這本書標價 350 元」，350 元是指？", options:["價格","價值"], answer:"價格", explanation:"標示在商品上的數字金額就是「價格」。" },
  { type:"multiple_choice", question:"「這本書讓我學到很多」，這句話說的是？", options:["價值","價格"], answer:"價值", explanation:"帶來的好處與意義就是「價值」，跟金額無關。" },
  { type:"multiple_choice", question:"超市標示：牛奶一瓶 45 元。45 元是？", options:["價格","價值"], answer:"價格", explanation:"商店標示的金額就是「價格」。" },
  { type:"multiple_choice", question:"奶奶說：「這個戒指對我很重要，因為是外婆留下來的。」這說的是？", options:["價值","價格"], answer:"價值", explanation:"對一個人的重要程度和意義就是「價值」。" },
  { type:"multiple_choice", question:"同一瓶水，超市賣 20 元，演唱會賣 80 元，改變的是？", options:["價格","價值"], answer:"價格", explanation:"水的標示金額因地點不同而改變，改變的是「價格」。" },
  { type:"multiple_choice", question:"「這雙鞋穿起來非常舒適」，這是描述鞋子的？", options:["價值","價格"], answer:"價值", explanation:"舒適是鞋子帶給人的好處，屬於「價值」。" },
  { type:"multiple_choice", question:"爸爸說：「這個雖然貴，但很值得。」他認為？", options:["價值高於價格","價格高於價值"], answer:"價值高於價格", explanation:"「值得」表示獲得的好處超過了付出的金額，即價值高於價格。" },
  { type:"multiple_choice", question:"商店打折：原價 500 元，現在 300 元。改變的是？", options:["價格","價值"], answer:"價格", explanation:"打折改變的是標示的金額，也就是「價格」。" },
  { type:"multiple_choice", question:"「這首歌讓我每次聽都很感動」，說的是這首歌的？", options:["價值","價格"], answer:"價值", explanation:"讓人感動的程度是「價值」的體現。" },
  { type:"multiple_choice", question:"「網路上賣 399 元」，這是什麼？", options:["價格","價值"], answer:"價格", explanation:"網路販售的金額就是「價格」。" },
  { type:"multiple_choice", question:"同一件古董，有人願意出 100 萬，有人只願意出 1000 元，不同的是他們對古董的？", options:["價值判斷","價格判斷"], answer:"價值判斷", explanation:"每個人對同一件東西的重視程度不同，這是「價值」的個人判斷。" },
  { type:"multiple_choice", question:"「這台玩具機器人售價 850 元」，850 元是？", options:["價格","價值"], answer:"價格", explanation:"商品的售價就是「價格」。" },
  { type:"multiple_choice", question:"小美說：「這個玩具沒什麼用，不值得買。」她是在評估玩具的？", options:["價值","價格"], answer:"價值", explanation:"「值不值得」是在判斷東西帶來的好處，也就是「價值」。" },
  { type:"multiple_choice", question:"爺爺留下的舊手錶，市場只賣 100 元，但對小明來說無價。這說明？", options:["價值和價格可以不同","價值等於價格"], answer:"價值和價格可以不同", explanation:"市場定的是「價格」，個人感受的是「價值」，兩者可以差很多。" },
  { type:"multiple_choice", question:"「這瓶飲料讓我在運動後恢復體力」，描述的是？", options:["價值","價格"], answer:"價值", explanation:"恢復體力是飲料帶來的功能與好處，屬於「價值」。" },
  { type:"multiple_choice", question:"商品標籤上寫的數字，是商品的？", options:["價格","價值"], answer:"價格", explanation:"標籤上的數字代表在市場上的售價，就是「價格」。" },
  { type:"multiple_choice", question:"媽媽說：「這個課程雖然要 5000 元，但學到的東西非常值錢。」她認為課程的什麼很高？", options:["價值","價格"], answer:"價值", explanation:"「學到的東西非常值錢」是在說課程帶來的收穫，也就是高「價值」。" },
  { type:"multiple_choice", question:"「今天特賣，所有商品打八折！」這是在改變商品的？", options:["價格","價值"], answer:"價格", explanation:"打折改變的是付錢的金額，也就是「價格」。" },
  { type:"multiple_choice", question:"「這個朋友對我的幫助很大」，說的是朋友帶來的？", options:["價值","價格"], answer:"價值", explanation:"朋友的幫助是無形的好處，屬於「價值」的概念。" },
  { type:"multiple_choice", question:"市場上，賣方定的數字叫做？", options:["價格","價值"], answer:"價格", explanation:"賣方在市場上標示的金額就是商品的「價格」。" }
];

export const exchange_vs_money = [
  { type:"multiple_choice", question:"小明用三顆彈珠換小華的橡皮擦，這是？", options:["交換","使用金錢"], answer:"交換", explanation:"用物品直接換物品，不涉及金錢，就是「交換」（以物易物）。" },
  { type:"multiple_choice", question:"去超市用 50 元買了一瓶飲料，這是？", options:["使用金錢","交換"], answer:"使用金錢", explanation:"用錢幣購買商品，是「使用金錢」進行交易。" },
  { type:"multiple_choice", question:"古代人用一袋米換一塊布，這是？", options:["交換（以物易物）","使用金錢"], answer:"交換（以物易物）", explanation:"沒有金錢出現，直接用物品換物品，就是「以物易物」的交換。" },
  { type:"multiple_choice", question:"金錢的主要功能是什麼？", options:["讓交易更方便","讓人變得更有權力"], answer:"讓交易更方便", explanation:"金錢是讓交換更便利的工具，解決了以物易物的麻煩。" },
  { type:"multiple_choice", question:"刷卡買了一件衣服，這是？", options:["使用金錢","交換"], answer:"使用金錢", explanation:"刷卡是電子化的付款方式，仍屬於「使用金錢」。" },
  { type:"multiple_choice", question:"用一本舊書換朋友的漫畫，這是？", options:["交換","使用金錢"], answer:"交換", explanation:"書換書，沒有使用金錢，是「交換」。" },
  { type:"multiple_choice", question:"在便利商店掃描 QR code 付款，這是？", options:["使用金錢","交換"], answer:"使用金錢", explanation:"掃碼付款是現代金錢的使用方式，仍屬於「使用金錢」。" },
  { type:"multiple_choice", question:"以物易物最大的缺點是什麼？", options:["雙方都需要對方的東西才能成立","物品容易壞掉"], answer:"雙方都需要對方的東西才能成立", explanation:"以物易物需要「雙重巧合」，雙方剛好都想要對方的東西，這非常困難。" },
  { type:"multiple_choice", question:"金錢和以物易物相比，金錢最大的優點是？", options:["可以統一衡量所有商品的價值","金錢本身很漂亮"], answer:"可以統一衡量所有商品的價值", explanation:"金錢提供了統一的衡量標準，讓各種商品都能用數字比較。" },
  { type:"multiple_choice", question:"小美用她的便當換小華的蛋糕，這叫做？", options:["交換","消費"], answer:"交換", explanation:"食物換食物，不涉及金錢，是「交換」。" },
  { type:"multiple_choice", question:"硬幣和紙鈔都是什麼的形式？", options:["金錢","交換"], answer:"金錢", explanation:"硬幣和紙鈔都是「金錢」的實體形式。" },
  { type:"multiple_choice", question:"農夫用小麥換鐵匠的農具，這是什麼時代常見的做法？", options:["以物易物的交換","使用金錢購買"], answer:"以物易物的交換", explanation:"金錢出現之前，人們用自己有的東西換需要的東西，叫「以物易物」。" },
  { type:"multiple_choice", question:"「交換」和「使用金錢」最根本的差別是？", options:["交換不用金錢，直接換物品","交換需要更多錢"], answer:"交換不用金錢，直接換物品", explanation:"以物易物的交換不涉及金錢，直接用東西換東西。" },
  { type:"multiple_choice", question:"爸爸幫鄰居修水管，鄰居給爸爸幾顆雞蛋，這是？", options:["交換（服務換物品）","使用金錢"], answer:"交換（服務換物品）", explanation:"用勞動服務換取物品，也是一種「交換」方式。" },
  { type:"multiple_choice", question:"電子支付（如 Line Pay）是哪一類行為？", options:["使用金錢","交換"], answer:"使用金錢", explanation:"電子支付是金錢的數位形式，仍是「使用金錢」。" },
  { type:"multiple_choice", question:"金錢最早出現，是為了解決什麼問題？", options:["以物易物的不方便","讓人更有錢"], answer:"以物易物的不方便", explanation:"金錢是人類為了讓「交換」更方便而發明的工具。" },
  { type:"multiple_choice", question:"小明用功課幫助解答換同學的飲料，這是？", options:["交換","收入"], answer:"交換", explanation:"用服務換物品，是一種廣義的「交換」。" },
  { type:"multiple_choice", question:"銀行裡的存款是什麼的一種形式？", options:["金錢","交換"], answer:"金錢", explanation:"銀行存款是以數位方式保存的「金錢」。" },
  { type:"multiple_choice", question:"市場上賣家和買家之間發生的，通常是？", options:["使用金錢的交易","以物易物"], answer:"使用金錢的交易", explanation:"現代市場大多使用金錢進行交易，而非以物易物。" },
  { type:"multiple_choice", question:"如果你用畫圖的服務換朋友幫你寫作業，這是？", options:["交換","借貸"], answer:"交換", explanation:"服務換服務，是一種廣義的「交換」行為。" }
];

export const spending_vs_consumption = [
  { type:"multiple_choice", question:"花了 30 元買早餐並吃掉，「花了 30 元」這個動作是？", options:["支出","消費"], answer:"支出", explanation:"花錢的動作是「支出」，吃早餐才是「消費」。" },
  { type:"multiple_choice", question:"花了 30 元買早餐並吃掉，「吃掉早餐」這個動作是？", options:["消費","支出"], answer:"消費", explanation:"實際使用或享用商品的過程是「消費」。" },
  { type:"multiple_choice", question:"去圖書館免費借書來看，這是？", options:["消費但沒有支出","支出但沒有消費"], answer:"消費但沒有支出", explanation:"看書是消費（使用服務），但免費借書不需要花錢，所以沒有支出。" },
  { type:"multiple_choice", question:"付水電費，這是？", options:["支出","消費"], answer:"支出", explanation:"付錢的行為是「支出」。" },
  { type:"multiple_choice", question:"「支出」關注的是？", options:["花掉多少錢","用了什麼東西"], answer:"花掉多少錢", explanation:"支出強調的是金錢的流出，重點在金額。" },
  { type:"multiple_choice", question:"「消費」強調的是？", options:["使用或享用商品和服務","花了多少錢"], answer:"使用或享用商品和服務", explanation:"消費的重點是實際使用或享用的行為。" },
  { type:"multiple_choice", question:"用免費的 Wi-Fi 上網，這是？", options:["消費但沒有支出","支出但沒有消費"], answer:"消費但沒有支出", explanation:"使用網路服務是消費，但不需要付錢，所以沒有支出。" },
  { type:"multiple_choice", question:"花 200 元買了一本書，放在書架上從來不看，這是？", options:["有支出，但沒有消費","有消費，但沒有支出"], answer:"有支出，但沒有消費", explanation:"花了錢（支出），但沒有實際使用（消費）。" },
  { type:"multiple_choice", question:"繳學費屬於什麼？", options:["支出","收入"], answer:"支出", explanation:"繳費是錢的流出，屬於「支出」。" },
  { type:"multiple_choice", question:"吃掉一個免費試吃的蛋糕，這是？", options:["消費但沒有支出","支出但沒有消費"], answer:"消費但沒有支出", explanation:"享用蛋糕是消費，但試吃免費，所以沒有支出。" },
  { type:"multiple_choice", question:"花 80 元看電影並看完，這是？", options:["同時有支出和消費","只有支出"], answer:"同時有支出和消費", explanation:"花 80 元是支出，看電影是消費，兩者都發生了。" },
  { type:"multiple_choice", question:"在公園免費玩溜滑梯，這是？", options:["消費（使用設施）但無支出","支出和消費都有"], answer:"消費（使用設施）但無支出", explanation:"使用公園設施是消費，但不需要付費，所以沒有支出。" },
  { type:"multiple_choice", question:"每月付房租，這屬於？", options:["支出","消費"], answer:"支出", explanation:"付錢是「支出」，居住在房子裡才是「消費」。" },
  { type:"multiple_choice", question:"小明說：「我花了 50 元。」他在說的是？", options:["支出","消費"], answer:"支出", explanation:"提到花了多少錢，是在說「支出」的金額。" },
  { type:"multiple_choice", question:"每天上學騎腳踏車，這是？", options:["消費（使用腳踏車）","支出"], answer:"消費（使用腳踏車）", explanation:"使用腳踏車是「消費」，買腳踏車時花的錢才是「支出」。" },
  { type:"multiple_choice", question:"「消費」可以不花錢嗎？", options:["可以，例如使用免費服務","不行，一定要花錢"], answer:"可以，例如使用免費服務", explanation:"消費是使用行為，不一定需要付錢。例如看免費影片也是消費。" },
  { type:"multiple_choice", question:"「支出」一定需要？", options:["花錢","使用東西"], answer:"花錢", explanation:"支出就是錢的流出，一定涉及金錢的支付。" },
  { type:"multiple_choice", question:"用完一支鉛筆，這是？", options:["消費（使用掉）","支出（花了錢）"], answer:"消費（使用掉）", explanation:"把東西用完是「消費」，買鉛筆時花的錢才是「支出」。" },
  { type:"multiple_choice", question:"收到生日禮物並玩了它，這是？", options:["消費但無支出","有支出也有消費"], answer:"消費但無支出", explanation:"玩禮物是消費，但自己沒有花錢買，所以沒有支出。" },
  { type:"multiple_choice", question:"以下哪一項最準確描述「支出」？", options:["錢從口袋裡流出去","享受一件東西"], answer:"錢從口袋裡流出去", explanation:"支出的核心是金錢的流出，不論買什麼。" }
];

export const budget_vs_saving_vs_record = [
  { type:"multiple_choice", question:"「這個月零用錢最多花 300 元」，這是在做？", options:["預算","記帳"], answer:"預算", explanation:"事先決定花費上限就是「預算」。" },
  { type:"multiple_choice", question:"「每週把零用錢存下 50 元」，這是？", options:["儲蓄","預算"], answer:"儲蓄", explanation:"把錢存起來不花掉就是「儲蓄」。" },
  { type:"multiple_choice", question:"「今天買早餐花了 35 元，寫在筆記本上」，這是？", options:["記帳","預算"], answer:"記帳", explanation:"記錄實際花了多少錢就是「記帳」。" },
  { type:"multiple_choice", question:"「計畫這個月旅行花費不超過 2000 元」，這是？", options:["預算","儲蓄"], answer:"預算", explanation:"提前計畫花費的上限就是「預算」。" },
  { type:"multiple_choice", question:"「把紅包錢放到撲滿裡」，這是？", options:["儲蓄","記帳"], answer:"儲蓄", explanation:"把錢存起來不使用就是「儲蓄」。" },
  { type:"multiple_choice", question:"「用 App 記下每天花了多少錢」，這是？", options:["記帳","儲蓄"], answer:"記帳", explanation:"記錄花費明細就是「記帳」。" },
  { type:"multiple_choice", question:"預算、儲蓄、記帳，哪一個是「事前計畫」？", options:["預算","記帳"], answer:"預算", explanation:"預算是在消費前先計畫，屬於事前規劃。" },
  { type:"multiple_choice", question:"預算、儲蓄、記帳，哪一個是「事後記錄」？", options:["記帳","預算"], answer:"記帳", explanation:"記帳是在消費後記錄花了什麼，屬於事後追蹤。" },
  { type:"multiple_choice", question:"「儲蓄」的目的通常是？", options:["累積資金以備將來使用","記錄花費"], answer:"累積資金以備將來使用", explanation:"儲蓄是把錢留下來，為未來的需求或目標做準備。" },
  { type:"multiple_choice", question:"小美說：「我要把每個月零用錢的一半存起來。」她在做？", options:["儲蓄","記帳"], answer:"儲蓄", explanation:"把一部分錢存起來就是「儲蓄」。" },
  { type:"multiple_choice", question:"「記帳」最主要的功能是？", options:["了解自己的錢花在哪裡","增加收入"], answer:"了解自己的錢花在哪裡", explanation:"記帳幫助我們追蹤花費，了解金錢的去向。" },
  { type:"multiple_choice", question:"小明月初設定：「午餐每天不超過 60 元。」這是在做？", options:["預算","記帳"], answer:"預算", explanation:"設定每日花費上限是「預算」規劃。" },
  { type:"multiple_choice", question:"在手機上用記帳 App 看見「本月花費 1200 元」，這是？", options:["記帳的結果","預算的結果"], answer:"記帳的結果", explanation:"統計實際花費是「記帳」功能的成果。" },
  { type:"multiple_choice", question:"「預算」和「記帳」最大的差別是？", options:["預算是計畫，記帳是記錄","預算是存錢，記帳是花錢"], answer:"預算是計畫，記帳是記錄", explanation:"預算是事前規劃，記帳是事後記錄，兩者時間點不同。" },
  { type:"multiple_choice", question:"想要存錢買一台腳踏車，每個月存 200 元，這是？", options:["儲蓄","預算"], answer:"儲蓄", explanation:"為了目標把錢存起來就是「儲蓄」。" },
  { type:"multiple_choice", question:"學校老師說：「管好金錢，先要知道自己花了多少。」這是在強調？", options:["記帳的重要性","儲蓄的重要性"], answer:"記帳的重要性", explanation:"了解花費狀況就是記帳的核心目的。" },
  { type:"multiple_choice", question:"以下哪個是正確的順序？", options:["先預算，後消費，再記帳","先記帳，後消費，再預算"], answer:"先預算，後消費，再記帳", explanation:"好的理財習慣是先計畫（預算），消費後再記錄（記帳）。" },
  { type:"multiple_choice", question:"小玲說：「我把今天買文具的收據留下來，月底再統計。」她在做？", options:["記帳","預算"], answer:"記帳", explanation:"保存收據並統計花費就是「記帳」。" },
  { type:"multiple_choice", question:"儲蓄的錢，通常應該？", options:["不輕易花掉，留作日後使用","馬上再花掉"], answer:"不輕易花掉，留作日後使用", explanation:"儲蓄的意義在於把錢保留下來，不立即花掉。" },
  { type:"multiple_choice", question:"預算、儲蓄、記帳三者合起來，能幫助我們？", options:["更有效管理金錢","讓錢自動增加"], answer:"更有效管理金錢", explanation:"三者互相配合，讓我們更清楚地計畫、追蹤和累積金錢。" }
];