// 題庫 Part 3：風險vs不確定性、營收vs利潤、成本vs費用、供給vs需求、個人價值vs市場價值

export const risk_vs_uncertainty = [
  { type:"multiple_choice", question:"「骰子擲出 1 的機率是 1/6」，這是？", options:["可計算的風險","不確定性"], answer:"可計算的風險", explanation:"可以用數學計算機率的情況屬於「風險」，可量化。" },
  { type:"multiple_choice", question:"「不知道明年的經濟狀況會如何」，這是？", options:["不確定性","可計算的風險"], answer:"不確定性", explanation:"無法預測或計算的情況叫「不確定性」。" },
  { type:"multiple_choice", question:"保險公司可以計算車禍的發生機率，這屬於？", options:["風險（可量化）","不確定性"], answer:"風險（可量化）", explanation:"保險公司用統計數據計算出機率，屬於「可量化的風險」。" },
  { type:"multiple_choice", question:"「不知道新創公司會不會成功」，這是？", options:["不確定性","已知風險"], answer:"不確定性", explanation:"新創公司的結果無法預測，難以量化，屬於「不確定性」。" },
  { type:"multiple_choice", question:"風險和不確定性最主要的差別是？", options:["風險可以計算機率，不確定性無法計算","它們完全一樣"], answer:"風險可以計算機率，不確定性無法計算", explanation:"風險是可量化的，不確定性是無法量化的未知。" },
  { type:"multiple_choice", question:"「這款遊戲有 30% 的機率打贏最終 Boss」，這是？", options:["風險（可計算）","不確定性"], answer:"風險（可計算）", explanation:"有具體數字的機率就是「風險」的量化表現。" },
  { type:"multiple_choice", question:"「不知道明天會不會發生地震」，這是？", options:["不確定性","確定的風險"], answer:"不確定性", explanation:"地震的發生時間難以精確預測，屬於「不確定性」。" },
  { type:"multiple_choice", question:"「抽獎中獎率 10%」，這是？", options:["風險（可量化）","不確定性"], answer:"風險（可量化）", explanation:"已知中獎率是可計算的，屬於「風險」。" },
  { type:"multiple_choice", question:"投資一家新公司，完全不知道未來會怎樣，這是？", options:["不確定性","可預測的風險"], answer:"不確定性", explanation:"完全無法預知結果的情況是「不確定性」。" },
  { type:"multiple_choice", question:"「健保統計顯示，40 歲男性患心臟病的機率是 2%」，這是？", options:["可量化的風險","不確定性"], answer:"可量化的風險", explanation:"用數據算出的機率是「可量化的風險」。" },
  { type:"multiple_choice", question:"一個企業家說：「我不確定市場明年的走向。」這說明他面對的是？", options:["不確定性","已知風險"], answer:"不確定性", explanation:"無法預知的市場未來屬於「不確定性」。" },
  { type:"multiple_choice", question:"「每 100 位飛機乘客中，1 位行李可能遺失」，這是？", options:["風險","不確定性"], answer:"風險", explanation:"有具體統計數字的是「風險」，可以用來計算保險費等。" },
  { type:"multiple_choice", question:"保險公司為什麼可以設定保費？", options:["因為他們能計算風險機率","因為他們猜不到未來"], answer:"因為他們能計算風險機率", explanation:"保險公司用統計數據算出各種事件的機率，再根據「風險」定價。" },
  { type:"multiple_choice", question:"「這次考試可能會考哪些題目，完全不知道」，這是？", options:["不確定性","確定的風險"], answer:"不確定性", explanation:"完全不知道結果，無法量化，屬於「不確定性」。" },
  { type:"multiple_choice", question:"以下哪個是「風險」而非「不確定性」？", options:["硬幣正反面各 50% 機率","不知道誰會贏得選舉"], answer:"硬幣正反面各 50% 機率", explanation:"硬幣結果有精確機率，屬於「風險」；選舉結果難以精確量化。" },
  { type:"multiple_choice", question:"面對不確定性，我們通常的做法是？", options:["做好準備應對各種可能","直接忽略"], answer:"做好準備應對各種可能", explanation:"無法精確預測，但可以廣泛準備，降低不確定性的影響。" },
  { type:"multiple_choice", question:"面對已知的「風險」，我們通常可以？", options:["計算機率並做相應的保障","完全避免"], answer:"計算機率並做相應的保障", explanation:"風險可量化，所以可以用保險等工具來管理。" },
  { type:"multiple_choice", question:"「不確定性」比「風險」更難管理，因為？", options:["不確定性無法量化或預測","不確定性損失一定更大"], answer:"不確定性無法量化或預測", explanation:"無法計算機率，就很難用數學工具來管理或保障。" },
  { type:"multiple_choice", question:"一家公司決定是否進入全新的市場，這是面對？", options:["不確定性","可計算風險"], answer:"不確定性", explanation:"全新市場的結果難以精確預測，屬於「不確定性」。" },
  { type:"multiple_choice", question:"以下對「風險」的描述，哪個最正確？", options:["可以用機率表達的不確定情況","完全不能預測的事情"], answer:"可以用機率表達的不確定情況", explanation:"風險的特點是可以量化，用機率來表示發生的可能性。" }
];

export const revenue_vs_profit = [
  { type:"multiple_choice", question:"一家文具店一個月賣出所有商品共賺了 50000 元，這是？", options:["營收","利潤"], answer:"營收", explanation:"銷售商品的總收入叫做「營收」，還未扣除成本。" },
  { type:"multiple_choice", question:"文具店一個月營收 50000 元，扣掉各種費用 40000 元後，剩下的 10000 元是？", options:["利潤","營收"], answer:"利潤", explanation:"營收扣除所有成本費用後剩下的才是「利潤」。" },
  { type:"multiple_choice", question:"「營收」和「利潤」哪個通常比較大？", options:["營收","利潤"], answer:"營收", explanation:"營收是總收入，利潤是扣完費用後的剩餘，所以營收通常較大。" },
  { type:"multiple_choice", question:"一杯手搖飲賣 60 元，材料費 20 元，剩下的 40 元是？", options:["毛利潤","營收"], answer:"毛利潤", explanation:"賣價扣除直接成本的部分叫「毛利潤」，是利潤的一種。" },
  { type:"multiple_choice", question:"小美做了 10 個手工餅乾，每個賣 50 元，她的「營收」是？", options:["500 元","500 元扣除材料費"], answer:"500 元", explanation:"營收是銷售的總金額，不用扣成本，所以是 10×50=500 元。" },
  { type:"multiple_choice", question:"小美的餅乾材料費共 200 元，她的「利潤」是？", options:["300 元（500 - 200）","500 元"], answer:"300 元（500 - 200）", explanation:"利潤 = 營收 - 成本 = 500 - 200 = 300 元。" },
  { type:"multiple_choice", question:"一家公司說：「我們這季的業績很好。」他們通常是在說？", options:["營收","純利潤"], answer:"營收", explanation:"「業績」通常是指銷售額，也就是「營收」。" },
  { type:"multiple_choice", question:"「這家公司雖然營收很高，但幾乎沒有利潤。」這代表？", options:["成本費用很高","賣得不夠好"], answer:"成本費用很高", explanation:"高營收但低利潤，通常是因為成本費用太高，吃掉了大部分收入。" },
  { type:"multiple_choice", question:"以下哪個公式正確？", options:["利潤 = 營收 - 成本","利潤 = 營收 + 成本"], answer:"利潤 = 營收 - 成本", explanation:"利潤就是收入扣掉所有費用後剩下的金額。" },
  { type:"multiple_choice", question:"一家店的營收是 100 萬，但成本是 110 萬，這家店是？", options:["虧損（負利潤）","有盈利"], answer:"虧損（負利潤）", explanation:"成本大於營收，就是虧損，利潤為負數。" },
  { type:"multiple_choice", question:"老闆最關心的應該是？", options:["利潤（實際賺到的）","營收（賣了多少）"], answer:"利潤（實際賺到的）", explanation:"最終進口袋的錢才是最重要的，所以老闆更關心「利潤」。" },
  { type:"multiple_choice", question:"「毛利」和「淨利」都是？", options:["利潤的不同計算方式","營收的別稱"], answer:"利潤的不同計算方式", explanation:"毛利是扣除直接成本，淨利是扣除所有費用，都是利潤的形式。" },
  { type:"multiple_choice", question:"攤販一天賣出 2000 元的商品，這 2000 元是？", options:["營收","利潤"], answer:"營收", explanation:"賣出商品的總金額就是「營收」。" },
  { type:"multiple_choice", question:"攤販成本 1400 元，賣了 2000 元，利潤是？", options:["600 元","2000 元"], answer:"600 元", explanation:"利潤 = 2000 - 1400 = 600 元。" },
  { type:"multiple_choice", question:"以下哪一個會讓利潤提高？", options:["降低成本","提高成本"], answer:"降低成本", explanation:"在營收不變的情況下，降低成本可以增加利潤。" },
  { type:"multiple_choice", question:"「我這個月賺了很多」，指的通常是？", options:["利潤高","營收高"], answer:"利潤高", explanation:"「賺到」的錢是扣掉成本後的利潤，而非總收入。" },
  { type:"multiple_choice", question:"公司的「財務報表」中，「利潤」通常叫做？", options:["淨利","總收入"], answer:"淨利", explanation:"扣除所有成本和費用後的利潤，在財務上叫「淨利」。" },
  { type:"multiple_choice", question:"小華賣貼紙，一包賣 20 元，買進成本 15 元，每包利潤是？", options:["5 元","20 元"], answer:"5 元", explanation:"利潤 = 賣價 - 成本 = 20 - 15 = 5 元。" },
  { type:"multiple_choice", question:"一家公司說「我們這季的利潤翻倍」，這代表？", options:["扣除成本後賺到的錢是上季的兩倍","他們的銷售量增加兩倍"], answer:"扣除成本後賺到的錢是上季的兩倍", explanation:"利潤翻倍是指淨賺的金額增加一倍，不一定是銷售量翻倍。" },
  { type:"multiple_choice", question:"「高營收但低利潤」通常表示什麼問題？", options:["成本費用太高","商品賣太便宜"], answer:"成本費用太高", explanation:"收入很多但花費也多，所以最後留下的利潤很少。" }
];

export const cost_vs_expense = [
  { type:"multiple_choice", question:"一家餐廳買食材用了 5000 元，這是？", options:["成本","費用"], answer:"成本", explanation:"為了生產商品或提供服務而花的錢，叫做「成本」。" },
  { type:"multiple_choice", question:"餐廳每月付的房租 10000 元，這是？", options:["費用（固定費用）","成本"], answer:"費用（固定費用）", explanation:"維持營業而支付的租金，屬於「費用」。" },
  { type:"multiple_choice", question:"「成本」通常是指？", options:["生產商品或服務所花的錢","辦公室的水電費"], answer:"生產商品或服務所花的錢", explanation:"成本是與「生產」直接相關的花費。" },
  { type:"multiple_choice", question:"公司的廣告費屬於？", options:["費用","成本"], answer:"費用", explanation:"廣告是支持業務運作的花費，屬於「費用」。" },
  { type:"multiple_choice", question:"製作玩具的材料費，是玩具的？", options:["成本","費用"], answer:"成本", explanation:"製造產品所需的材料費是「成本」的一部分。" },
  { type:"multiple_choice", question:"公司員工的薪水，屬於？", options:["費用（人力費用）","成本（材料成本）"], answer:"費用（人力費用）", explanation:"員工薪水是公司營運的人力費用，屬於「費用」。" },
  { type:"multiple_choice", question:"書包製造商採購布料的錢，這是書包的？", options:["成本","費用"], answer:"成本", explanation:"直接用於製造商品的材料費是「成本」。" },
  { type:"multiple_choice", question:"工廠的水電費屬於？", options:["費用（營運費用）","成本"], answer:"費用（營運費用）", explanation:"維持工廠運作的水電費是「費用」，不是直接製造產品的成本。" },
  { type:"multiple_choice", question:"賣一個蘋果派，麵粉、雞蛋、蘋果的費用是？", options:["成本（材料成本）","費用"], answer:"成本（材料成本）", explanation:"直接進入產品的原料費用是「成本」。" },
  { type:"multiple_choice", question:"麵包店老闆說：「我的成本很高。」這通常指？", options:["做麵包需要花很多材料費","廣告費很高"], answer:"做麵包需要花很多材料費", explanation:"成本指的是製作產品的直接花費。" },
  { type:"multiple_choice", question:"以下哪個是「費用」而非「成本」？", options:["每月辦公室租金","製造商品用的原料"], answer:"每月辦公室租金", explanation:"租金是維持業務運作的費用，不是直接製造成本。" },
  { type:"multiple_choice", question:"以下哪個是「成本」而非「費用」？", options:["製作手工皂的油脂原料","公司的保險費"], answer:"製作手工皂的油脂原料", explanation:"直接進入產品的材料是「成本」。" },
  { type:"multiple_choice", question:"「成本」和「費用」都是？", options:["花掉的錢","賺到的錢"], answer:"花掉的錢", explanation:"成本和費用都是支出，是花掉的錢，但用途和性質不同。" },
  { type:"multiple_choice", question:"降低成本，在其他條件不變的情況下，利潤會？", options:["提高","降低"], answer:"提高", explanation:"成本降低，意味著賣出同樣的東西能留下更多利潤。" },
  { type:"multiple_choice", question:"一家學校每月支付教室租金，這是學校的？", options:["費用","成本"], answer:"費用", explanation:"租金是維持學校運作的費用，屬於「費用」。" },
  { type:"multiple_choice", question:"手搖飲的珍珠、茶葉、糖是？", options:["成本（材料成本）","費用"], answer:"成本（材料成本）", explanation:"直接製作飲料所需的材料是「成本」。" },
  { type:"multiple_choice", question:"手搖飲店每月的清潔費屬於？", options:["費用（營運費用）","成本"], answer:"費用（營運費用）", explanation:"清潔費是維持店面運作的費用，不是直接製造飲料的成本。" },
  { type:"multiple_choice", question:"「固定費用」是指？", options:["不論生產量多少都要付的費用","隨生產量增減的費用"], answer:"不論生產量多少都要付的費用", explanation:"固定費用如租金，不管賣出多少都要付。" },
  { type:"multiple_choice", question:"「變動成本」是指？", options:["隨生產量增減的成本","固定不變的費用"], answer:"隨生產量增減的成本", explanation:"材料費等會隨生產量改變，是「變動成本」。" },
  { type:"multiple_choice", question:"了解成本和費用有什麼用？", options:["幫助計算利潤，做好財務管理","只對大公司有用"], answer:"幫助計算利潤，做好財務管理", explanation:"清楚成本和費用才能算出利潤，幫助更好地管理財務。" }
];

export const supply_vs_demand = [
  { type:"multiple_choice", question:"市場上消費者想買的商品數量叫做？", options:["需求","供給"], answer:"需求", explanation:"買方想要購買的數量就是「需求」。" },
  { type:"multiple_choice", question:"市場上生產者願意賣的商品數量叫做？", options:["供給","需求"], answer:"供給", explanation:"賣方願意提供的商品數量就是「供給」。" },
  { type:"multiple_choice", question:"颱風前大家搶買物資，物資的「需求」會？", options:["增加","減少"], answer:"增加", explanation:"颱風前大家擔心物資短缺，購買意願增加，「需求」上升。" },
  { type:"multiple_choice", question:"農夫大豐收，蔬菜的「供給」會？", options:["增加","減少"], answer:"增加", explanation:"豐收代表蔬菜大量生產，供應市場的數量增加，「供給」上升。" },
  { type:"multiple_choice", question:"需求增加但供給不變，商品價格通常會？", options:["上升","下降"], answer:"上升", explanation:"搶購的人多但商品量不變，賣方可以提高價格，所以價格上升。" },
  { type:"multiple_choice", question:"供給增加但需求不變，商品價格通常會？", options:["下降","上升"], answer:"下降", explanation:"商品太多賣不掉，賣方需要降價吸引買家，價格下降。" },
  { type:"multiple_choice", question:"限量版球鞋只有 100 雙，但有 10000 人想買，這是？", options:["供給遠小於需求","需求等於供給"], answer:"供給遠小於需求", explanation:"想買的人遠多於商品數量，屬於「供給不足，需求過剩」。" },
  { type:"multiple_choice", question:"限量版球鞋「供不應求」時，價格通常會？", options:["大幅上漲","大幅下跌"], answer:"大幅上漲", explanation:"搶手商品，賣家可以賣更高價，所以價格上漲。" },
  { type:"multiple_choice", question:"市場上蘋果豐收，「供給」增加，蘋果價格可能？", options:["下降","上升"], answer:"下降", explanation:"供給增加、需求不變，商品多了賣不掉，價格就會下降。" },
  { type:"multiple_choice", question:"「供需平衡」是指？", options:["供給量和需求量剛好相等","供給大於需求"], answer:"供給量和需求量剛好相等", explanation:"供需平衡時，市場處於穩定狀態，不會有太大的價格波動。" },
  { type:"multiple_choice", question:"流感季節，口罩需求大增，這是因為？", options:["消費者購買意願增加（需求增加）","口罩工廠增加（供給增加）"], answer:"消費者購買意願增加（需求增加）", explanation:"生病人數多，大家都想買口罩，是「需求」端的增加。" },
  { type:"multiple_choice", question:"新手機工廠增加，手機的「供給」增加，手機價格可能？", options:["下降","上升"], answer:"下降", explanation:"供給增加、需求不變，價格受到向下壓力，通常下降。" },
  { type:"multiple_choice", question:"超市打折，消費者購買量增加，這是因為價格下降後「需求量」？", options:["增加","減少"], answer:"增加", explanation:"價格下降通常讓更多人願意購買，需求量增加。" },
  { type:"multiple_choice", question:"「供給」是由哪一方決定的？", options:["賣方（生產者）","買方（消費者）"], answer:"賣方（生產者）", explanation:"供給是賣方決定要提供多少商品給市場。" },
  { type:"multiple_choice", question:"「需求」是由哪一方決定的？", options:["買方（消費者）","賣方（生產者）"], answer:"買方（消費者）", explanation:"需求是消費者想要購買的數量，由買方決定。" },
  { type:"multiple_choice", question:"颱風讓蔬菜田受損，蔬菜供給減少，蔬菜價格會？", options:["上升","下降"], answer:"上升", explanation:"供給減少、需求不變，商品變稀少，價格上漲。" },
  { type:"multiple_choice", question:"「物以稀為貴」說明的是？", options:["供給少的東西價格高","需求少的東西價格高"], answer:"供給少的東西價格高", explanation:"東西稀少（供給低），但需求不變，價格就會高。" },
  { type:"multiple_choice", question:"市場上有賣家就有「供給」，有買家就有「需求」，價格是由什麼決定的？", options:["供給和需求的平衡","只由賣家決定"], answer:"供給和需求的平衡", explanation:"市場價格是供需雙方互動的結果。" },
  { type:"multiple_choice", question:"夏天大家都想喝涼飲，飲料的「需求」會？", options:["增加","減少"], answer:"增加", explanation:"天氣熱，想喝涼飲的人增加，「需求」上升。" },
  { type:"multiple_choice", question:"了解「供給」和「需求」，最實際的用途是？", options:["幫助預測價格變化","讓人更聰明"], answer:"幫助預測價格變化", explanation:"了解供需關係，可以幫助我們預測和理解商品價格的變化。" }
];

export const personal_vs_market_value = [
  { type:"multiple_choice", question:"「這個玩具對我來說很特別，我非常珍惜它。」這說明的是？", options:["個人價值","市場價值"], answer:"個人價值", explanation:"個人對某樣東西的感受和重視程度，就是「個人價值」。" },
  { type:"multiple_choice", question:"「這台二手電腦在市場上可以賣 3000 元。」這是？", options:["市場價值","個人價值"], answer:"市場價值", explanation:"在市場上交易的價格，就是「市場價值」。" },
  { type:"multiple_choice", question:"奶奶的舊戒指在拍賣市場只值 500 元，但對小明來說無價，這說明？", options:["個人價值可以遠超市場價值","市場價值等於個人價值"], answer:"個人價值可以遠超市場價值", explanation:"情感上的意義可以讓個人價值遠超市場定價。" },
  { type:"multiple_choice", question:"「這幅畫在藝術市場的估價是 100 萬元。」這說的是？", options:["市場價值","個人價值"], answer:"市場價值", explanation:"市場上眾人認可的估價就是「市場價值」。" },
  { type:"multiple_choice", question:"小美說：「就算很多人不喜歡這部電影，我覺得它是最棒的。」這是？", options:["個人價值判斷","市場價值判斷"], answer:"個人價值判斷", explanation:"個人對事物的喜愛程度，不依賴市場認可，是「個人價值」。" },
  { type:"multiple_choice", question:"「股票市場上這支股票每股 50 元。」這代表它的？", options:["市場價值","個人價值"], answer:"市場價值", explanation:"市場上的成交價格代表「市場價值」。" },
  { type:"multiple_choice", question:"「個人價值」由什麼決定？", options:["個人的感受、喜好和經歷","市場的供需關係"], answer:"個人的感受、喜好和經歷", explanation:"個人價值是主觀的，由每個人自己的感受決定。" },
  { type:"multiple_choice", question:"「市場價值」由什麼決定？", options:["市場上的供給和需求","個人的感受"], answer:"市場上的供給和需求", explanation:"市場價值是客觀的，由市場上買賣雙方的交互決定。" },
  { type:"multiple_choice", question:"同一個東西，不同的人願意付的錢可能不同，這是因為？", options:["每個人的個人價值判斷不同","市場價值每天都在變"], answer:"每個人的個人價值判斷不同", explanation:"不同人對同樣東西有不同的個人感受，所以願意付的錢不同。" },
  { type:"multiple_choice", question:"「這個骨董在市場上估價 10 萬元」，是在說骨董的？", options:["市場價值","個人價值"], answer:"市場價值", explanation:"市場估價就是「市場價值」。" },
  { type:"multiple_choice", question:"一個人說：「就算很多人不喜歡這部電影，我覺得它是最棒的。」這是？", options:["個人價值判斷","市場價值判斷"], answer:"個人價值判斷", explanation:"不依賴大眾評價的個人喜好，就是「個人價值」。" },
  { type:"multiple_choice", question:"「個人價值」和「市場價值」哪個更客觀？", options:["市場價值","個人價值"], answer:"市場價值", explanation:"市場價值由多人決定，較為客觀；個人價值是主觀的。" },
  { type:"multiple_choice", question:"買家願意花高價買一件東西，說明這件東西的什麼高？", options:["對買家的個人價值","市場公定價格"], answer:"對買家的個人價值", explanation:"願意花高價，說明這件東西對他個人來說很有意義或效用。" },
  { type:"multiple_choice", question:"「市場價值」通常可以用什麼表示？", options:["金錢價格","個人感受"], answer:"金錢價格", explanation:"市場價值通常以市場交易價格（金錢）來衡量。" },
  { type:"multiple_choice", question:"一首老歌在串流平台播放量很低，但對某個人意義重大，這個人認為這首歌的「個人價值」？", options:["很高","很低"], answer:"很高", explanation:"播放量低是市場價值低，但個人感受的意義高，就是個人價值高。" },
  { type:"multiple_choice", question:"「個人價值」可以影響一個人的消費決定嗎？", options:["可以，個人認為值得就會購買","不行，只有市場價值影響購買"], answer:"可以，個人認為值得就會購買", explanation:"我們的消費決定很多時候取決於個人認為這樣東西對自己的意義。" },
  { type:"multiple_choice", question:"媽媽說：「這個牌子雖然貴，但我覺得品質很值得。」她在表達？", options:["個人價值判斷","市場價值判斷"], answer:"個人價值判斷", explanation:"個人認為品質值得付高價，是「個人價值」的表現。" },
  { type:"multiple_choice", question:"名牌包包的「市場價值」是由？", options:["市場上消費者和品牌商共同決定","只由買家決定"], answer:"市場上消費者和品牌商共同決定", explanation:"市場價值是供需雙方互動的結果。" },
  { type:"multiple_choice", question:"了解「個人價值」和「市場價值」的差別，能幫助我們？", options:["做更明智的消費決定","讓東西變得更貴"], answer:"做更明智的消費決定", explanation:"了解兩者的差別，能讓我們思考是真的需要，還是只是被市場炒作影響。" },
  { type:"multiple_choice", question:"「炒作」讓某個東西的市場價格飆高，但其實際功能沒有改變，這說明？", options:["市場價值可以脫離實際價值","個人價值決定一切"], answer:"市場價值可以脫離實際價值", explanation:"炒作可以讓市場價格遠超商品本身的功能價值，市場價值不一定反映真實效用。" }
];